import "./globals.css";
import AppBar from "@/components/AppBar";
import Providers from "@/components/Provider";

export const metadata = {
  title: " Authentication with Next-Auth and Next.js",
  description: "Generated by Zen",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AppBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
